# vim:ft=tmux
# Eldritch theme colors based on eldritch.nvim
thm_bg="#212337"
thm_fg="#ebfafa"
thm_cyan="#04d1f9"
thm_black="#171928"
thm_gray="#292e42"
thm_magenta="#a48cf2"
thm_pink="#f265b5"
thm_red="#f16c75"
thm_green="#37f499"
thm_yellow="#f1fc79"
thm_blue="#7081d0"
thm_orange="#f7c67f"
thm_black4="#3b4261"