require("colorscheme")
require("options")
require("keymaps")
-- import plugin's
require("plugins.packer-setup")
require("plugins.comment")
require("plugins.nvimtree")
require("plugins.lualine")
require("plugins.telescope")
require("plugins.nvim-cmp")
require("plugins.treesitter")
require("plugins.autopair")
require("plugins.lspconfig")
require("plugins.mason")
require("plugins.formatter")
require("plugins.gitsigns")
require("plugins.indent")
require("plugins.devicons")
