name: "Feature Request"
description: "Suggest an idea for this project"
labels: [enhancement]
body:
  - type: textarea
    id: describe-the-bug
    attributes:
      label: "Describe the feature"
      description: "A clear and concise description of what the feature is."
    validations:
      required: true
  - type: input
    id: project-template
    attributes:
      label: "Project Template"
      description: "Which project template and project template version is the issue about?"
    validations:
      required: true
