# style name or JSON path (default "auto")
style: "dark"
# mouse wheel support (TUI-mode only)
mouse: true
# use pager to display markdown
pager: true
# at which column should we word wrap?
width: 80
# show all files, including hidden and ignored.
all: true
# show line numbers (TUI-mode only)
showLineNumbers: true
# preserve newlines in the output
preserveNewLines: true
