-- NOTE: filename is intentionally kept as "ocoto.lua" to avoid disrupting lazy.nvim cache.
-- folke/gh.nvim has been disabled (see plugins/gh.lua) — it was conflicting with these mappings.
return {
    "pwntester/octo.nvim",
    -- lazy.nvim uses `dependencies`, not `requires`
    dependencies = {
        "nvim-lua/plenary.nvim",
        "nvim-telescope/telescope.nvim",
        "nvim-tree/nvim-web-devicons",
    },
    config = function()
        require("octo").setup({
            use_local_fs = false,
            enable_builtin = false,
            default_remote = { "upstream", "origin" },
            default_merge_method = "merge",
            default_delete_branch = false,
            ssh_aliases = {},
            picker = "telescope",
            picker_config = {
                use_emojis = false,
                search_static = true,
                mappings = {
                    open_in_browser = { lhs = "<C-b>", desc = "open issue in browser" },
                    copy_url        = { lhs = "<C-y>", desc = "copy url to system clipboard" },
                    copy_sha        = { lhs = "<C-e>", desc = "copy commit SHA to system clipboard" },
                    -- <C-o> was conflicting with vim's jump-backward; moved to <C-g>o
                    checkout_pr     = { lhs = "<C-g>o", desc = "checkout pull request" },
                    merge_pr        = { lhs = "<C-g>m", desc = "merge pull request" },
                },
                snacks = {
                    actions = {
                        issues = {},
                        pull_requests = {},
                        notifications = {},
                        issue_templates = {},
                        search = {},
                    },
                },
            },
            comment_icon = "▎",
            outdated_icon = "󰅒 ",
            resolved_icon = " ",
            reaction_viewer_hint_icon = " ",
            commands = {},
            users = "search",
            user_icon = " ",
            ghost_icon = "󰊠 ",
            copilot_icon = " ",
            timeline_marker = " ",
            timeline_indent = 2,
            use_timeline_icons = true,
            timeline_icons = {
                auto_squash = "  ",
                commit_push = "  ",
                comment_deleted = " ",
                force_push = "  ",
                draft = "  ",
                ready = " ",
                commit = "  ",
                deployed = "  ",
                issue_type = "  ",
                label = "  ",
                reference = "  ",
                project = "  ",
                connected = "  ",
                subissue = "  ",
                cross_reference = "  ",
                parent_issue = "  ",
                head_ref = "  ",
                pinned = "  ",
                milestone = "  ",
                renamed = "  ",
                automatic_base_change_succeeded = "  ",
                base_ref_changed = "  ",
                merged = { "  ", "OctoPurple" },
                closed = {
                    closed = { "  ", "OctoRed" },
                    completed = { "  ", "OctoPurple" },
                    not_planned = { "  ", "OctoGrey" },
                    duplicate = { "  ", "OctoGrey" },
                },
                reopened = { "  ", "OctoGreen" },
                assigned = "  ",
                review_requested = "  ",
            },
            right_bubble_delimiter = "",
            left_bubble_delimiter = "",
            github_hostname = "",
            snippet_context_lines = 4,
            gh_cmd = "gh",
            gh_env = {},
            timeout = 5000,
            default_to_projects_v2 = false,
            ui = {
                use_signcolumn = false,
                use_signstatus = true,
            },
            issues = {
                order_by = {
                    field = "CREATED_AT",
                    direction = "DESC",
                },
            },
            reviews = {
                auto_show_threads = true,
                focus = "right",
            },
            runs = {
                icons = {
                    pending = "🕖",
                    in_progress = "🔄",
                    failed = "❌",
                    succeeded = "",
                    skipped = "⏩",
                    cancelled = "✖",
                },
            },
            pull_requests = {
                order_by = {
                    field = "CREATED_AT",
                    direction = "DESC",
                },
                always_select_remote_on_create = false,
                use_branch_name_as_title = false,
            },
            notifications = {
                current_repo_only = false,
            },
            file_panel = {
                size = 10,
                use_icons = true,
            },
            colors = {
                white = "#ffffff",
                grey = "#2A354C",
                black = "#000000",
                red = "#fdb8c0",
                dark_red = "#da3633",
                green = "#acf2bd",
                dark_green = "#238636",
                yellow = "#d3c846",
                dark_yellow = "#735c0f",
                blue = "#58A6FF",
                dark_blue = "#0366d6",
                purple = "#6f42c1",
            },
            mappings_disable_default = false,
        })
    end,
}
