worktree-path = "{{ repo_path }}/../{{ branch | sanitize }}"

[commit.generation]
command = "ocr -c \"write a commit message and push\""

[post-switch]
tmux = "[ -n \"$TMUX\" ] && tmux rename-window \"$(basename $(dirname {{ repo_path }}))/{{ branch | sanitize }}\""
